package com.offlinekeyboard.ime.glide

import java.io.File
import java.io.InputStream

/**
 * The words a glide can decode to, and how often each is written.
 *
 * Backed by `assets/lexicon_en.tsv`, generated by `tools/build_lexicon.py` from Norvig's
 * count_1w.txt and web2. Committed rather than fetched: this app has no INTERNET permission and
 * could not download it if it wanted to.
 *
 * Two things about the shape of this class are load-bearing.
 *
 * **Words are stored twice, as spelled and as glided.** "I'm" is typed with an apostrophe and a
 * capital, but the finger only ever crosses `i` and `m`; the path has no idea the other two
 * characters exist. Keeping the pair means the decoder matches against letters and the keyboard
 * commits the spelling, with nothing in between having to guess.
 *
 * **The index is by first *and* last letter.** A glide's endpoints are the two parts of it the
 * user is most deliberate about -- the finger starts on a key and stops on a key, and the middle
 * is where it cuts corners. Bucketing on the pair turns a 40,000-word scan into roughly sixty
 * words per bucket, which is what makes decoding cheap enough to do on the UI thread at the
 * moment the finger lifts.
 */
class Lexicon private constructor(
    /** As typed: "I'm", "o'clock". */
    val words: List<String>,
    /** As glided: the a-z letters only, lowercased. "im", "oclock". */
    val letters: List<String>,
    /** 100 x log10 of the corpus count. Frequency in hundredths of a decade. */
    val logFrequency: IntArray,
    private val buckets: Map<Int, IntArray>,
) {

    val size: Int get() = words.size

    /** Word indices that begin with [first] and end with [last]. Empty when there are none. */
    fun bucket(first: Char, last: Char): IntArray = buckets[key(first, last)] ?: EMPTY

    /**
     * Writes this lexicon as an AOSP `.combined` dictionary, which is what swipe-library's
     * beam search reads.
     *
     * Derived rather than shipped as a second asset, so both decoders are constrained to exactly
     * the same words -- which is the only way the comparison between them measures decoding
     * rather than vocabulary. It costs about a tenth of a second, once, on first use.
     *
     * The `f=` field is AOSP's 0-255 frequency, and mapping our log-frequency onto it linearly is
     * the right shape: AOSP's own value is log-scaled too. The floor is 1 rather than 0 because
     * 0 is AOSP's "known but never offer this" value.
     */
    fun writeCombined(target: File) {
        if (logFrequency.isEmpty()) return
        var low = logFrequency[0]
        var high = logFrequency[0]
        logFrequency.forEach {
            if (it < low) low = it
            if (it > high) high = it
        }
        val span = (high - low).coerceAtLeast(1)
        target.parentFile?.mkdirs()
        target.bufferedWriter().use { out ->
            out.write("dictionary=main:en,locale=en,description=offline-keyboard,date=0,version=1\n")
            words.forEachIndexed { i, word ->
                // A comma would end the surface field early. Nothing in the generated asset has
                // one, and a word that did would silently truncate rather than fail.
                if (word.indexOf(',') >= 0) return@forEachIndexed
                val f = 1 + 254 * (logFrequency[i] - low) / span
                out.write(" word=")
                out.write(word)
                out.write(",f=")
                out.write(f.toString())
                out.write("\n")
            }
        }
    }

    companion object {
        private val EMPTY = IntArray(0)

        /**
         * A glide needs two keys to be a glide at all. One-letter entries ("a", "I") can only
         * ever be typed by tapping, and having them here would let a sloppy tap that drifted a
         * key's width decode as a word.
         */
        private const val MIN_LETTERS = 2

        private fun key(first: Char, last: Char) = (first - 'a') * 26 + (last - 'a')

        fun load(input: InputStream): Lexicon {
            val words = ArrayList<String>(48_000)
            val letters = ArrayList<String>(48_000)
            val frequencies = ArrayList<Int>(48_000)
            val grouped = HashMap<Int, MutableList<Int>>()

            input.bufferedReader().useLines { lines -> lines.forEach { line -> read(line, words, letters, frequencies, grouped) } }

            return Lexicon(
                words = words,
                letters = letters,
                logFrequency = IntArray(frequencies.size) { frequencies[it] },
                buckets = grouped.mapValues { (_, list) -> IntArray(list.size) { list[it] } },
            )
        }

        private fun read(
            line: String,
            words: MutableList<String>,
            letters: MutableList<String>,
            frequencies: MutableList<Int>,
            grouped: MutableMap<Int, MutableList<Int>>,
        ) {
            if (line.isEmpty() || line[0] == '#') return
            val tab = line.indexOf('\t')
            if (tab <= 0) return
            val word = line.substring(0, tab)
            val frequency = line.substring(tab + 1).trim().toIntOrNull() ?: return
            val glided = word.lowercase().filter { it in 'a'..'z' }
            if (glided.length < MIN_LETTERS) return

            val index = words.size
            words += word
            letters += glided
            frequencies += frequency
            grouped.getOrPut(key(glided.first(), glided.last())) { ArrayList() } += index
        }

        /** For tests and for a build with no asset: a lexicon over a handful of words. */
        fun of(vararg entries: Pair<String, Int>): Lexicon =
            load(entries.joinToString("\n") { "${it.first}\t${it.second}" }.byteInputStream())
    }
}

/** The asset [Lexicon.load] reads, generated by `tools/build_lexicon.py`. */
const val LEXICON_ASSET = "lexicon_en.tsv"
