package com.offlinekeyboard.ime.glide

import java.io.File
import java.io.InputStream

/**
 * The words a glide can decode to, and how often each is written.
 *
 * Backed by `assets/lexicon_en.tsv`, generated by `tools/build_lexicon.py` from Norvig's
 * count_1w.txt and web2. Committed rather than fetched: this app has no INTERNET permission and
 * could not download it if it wanted to.
 *
 * Two things about the shape of this class are load-bearing.
 *
 * **Words are stored twice, as spelled and as glided.** "I'm" is typed with an apostrophe and a
 * capital, but the finger only ever crosses `i` and `m`; the path has no idea the other two
 * characters exist. Keeping the pair means the decoder matches against letters and the keyboard
 * commits the spelling, with nothing in between having to guess.
 *
 * **The index is by first *and* last letter.** A glide's endpoints are the two parts of it the
 * user is most deliberate about -- the finger starts on a key and stops on a key, and the middle
 * is where it cuts corners. Bucketing on the pair turns a 40,000-word scan into roughly sixty
 * words per bucket, which is what makes decoding cheap enough to do on the UI thread at the
 * moment the finger lifts.
 */
class Lexicon private constructor(
    /** As typed: "I'm", "o'clock". */
    val words: List<String>,
    /** As glided: the a-z letters only, lowercased. "im", "oclock". */
    val letters: List<String>,
    /** 100 x log10 of the corpus count. Frequency in hundredths of a decade. */
    val logFrequency: IntArray,
    private val buckets: Map<Int, IntArray>,
) {

    /**
     * Glided form -> spellings, most frequent first.
     *
     * Only the forms that need it are stored. For the overwhelming majority the spelling is the
     * glided form unchanged, and an entry saying so would be 40,000 strings to say nothing; the
     * absent case is handled by [spellings] returning the word the decoder already had.
     */
    private val spelledAs: Map<String, List<String>> = buildSpellings()

    val size: Int get() = words.size

    /** Word indices that begin with [first] and end with [last]. Empty when there are none. */
    fun bucket(first: Char, last: Char): IntArray = buckets[key(first, last)] ?: EMPTY

    /**
     * The spellings of a glided form, most frequent first.
     *
     * This exists because a decoder only ever answers in letters. A finger crossing `d-o-n-t` has
     * no way to express the apostrophe in "don't" -- the key is not on the path and for most
     * layouts not on the keyboard -- so every engine here decodes to the glided form and something
     * afterwards has to put the spelling back. [Lexicon] is where the pair already lives, so it is
     * where the question gets answered rather than in each engine separately.
     *
     * Most of the time the answer is one word and it is the word itself. The interesting cases are
     * the 42 glided forms whose only spelling carries an apostrophe -- "dont" and "wheres" are not
     * English, and a decoder that emits them is emitting a word no one can have meant -- and the
     * ten that are genuinely two words, where "its" and "it's" are both real and the choice is the
     * caller's to offer rather than this class's to make silently.
     *
     * A form with nothing to restore answers with itself, so callers can map every decode through
     * this without asking first whether it was one of the interesting ones.
     */
    fun spellings(glided: String): List<String> = spelledAs[glided] ?: listOf(glided)

    /** Word -> its index, for the exact-match lookups the suggestion bar makes. */
    private val byWord: Map<String, Int> by lazy {
        HashMap<String, Int>(words.size * 2).apply {
            words.forEachIndexed { i, w -> putIfAbsent(w.lowercase(), i) }
        }
    }

    /**
     * `ln P(word)` for [word], or null when it is not an English word.
     *
     * Used by the unified suggestion bar to weigh "these letters are English" against "these
     * letters are pinyin" -- `you` and `women` are both, and without this the Chinese reading
     * wins on raw frequency. See [com.offlinekeyboard.ime.candidates.UnifiedCandidates].
     *
     * [logFrequency] is `100 * log10(count)`, so this is a change of base and a division by the
     * corpus total. [LOG_CORPUS_TOTAL] is that total's natural log, implied by the commonest
     * entry being about 6% of tokens -- the same reasoning the pinyin decoder's CORPUS_TOTAL
     * rests on, and like it a constant factor that shifts every English word equally.
     */
    fun logProbability(word: String): Float? {
        val i = byWord[word.lowercase()] ?: return null
        return logFrequency[i] * LN10_PER_CENTIDECADE - LOG_CORPUS_TOTAL
    }

    private fun buildSpellings(): Map<String, List<String>> {
        // Pass one: which glided forms are spelled differently from how they are glided. Only
        // those need an entry at all.
        val interesting = HashSet<String>()
        letters.forEachIndexed { i, glided -> if (glided != words[i]) interesting += glided }

        // Pass two: collect *every* spelling of those forms, including the one that is identical
        // to the glided form. Missing it would turn "its" into "it's" outright, when the truth is
        // that both are words and the caller should see both.
        val grouped = HashMap<String, MutableList<Int>>(interesting.size * 2)
        letters.forEachIndexed { i, glided ->
            if (glided in interesting) grouped.getOrPut(glided) { ArrayList(2) } += i
        }

        return grouped.mapValues { (_, indices) ->
            indices.sortedByDescending { logFrequency[it] }.map { words[it] }.distinct()
        }
    }

    /**
     * Writes this lexicon as an AOSP `.combined` dictionary, which is what swipe-library's
     * beam search reads.
     *
     * Derived rather than shipped as a second asset, so both decoders are constrained to exactly
     * the same words -- which is the only way the comparison between them measures decoding
     * rather than vocabulary. It costs about a tenth of a second, once, on first use.
     *
     * The `f=` field is AOSP's 0-255 frequency, and mapping our log-frequency onto it linearly is
     * the right shape: AOSP's own value is log-scaled too. The floor is 1 rather than 0 because
     * 0 is AOSP's "known but never offer this" value.
     */
    fun writeCombined(target: File) {
        if (logFrequency.isEmpty()) return
        var low = logFrequency[0]
        var high = logFrequency[0]
        logFrequency.forEach {
            if (it < low) low = it
            if (it > high) high = it
        }
        val span = (high - low).coerceAtLeast(1)
        target.parentFile?.mkdirs()
        target.bufferedWriter().use { out ->
            out.write("dictionary=main:en,locale=en,description=offline-keyboard,date=0,version=1\n")
            words.forEachIndexed { i, word ->
                // A comma would end the surface field early. Nothing in the generated asset has
                // one, and a word that did would silently truncate rather than fail.
                if (word.indexOf(',') >= 0) return@forEachIndexed
                val f = 1 + 254 * (logFrequency[i] - low) / span
                out.write(" word=")
                out.write(word)
                out.write(",f=")
                out.write(f.toString())
                out.write("\n")
            }
        }
    }

    companion object {
        private val EMPTY = IntArray(0)

        /**
         * Converts [logFrequency]'s unit -- hundredths of a decade -- into nats: `ln(10) / 100`.
         */
        private const val LN10_PER_CENTIDECADE = 0.0230258509f

        /**
         * `ln` of the English corpus total implied by the lexicon's own scale.
         *
         * The commonest entry scores 1036, i.e. a count of 10^10.36, and the commonest English
         * word is around 6% of tokens; that puts the corpus near 3.8e11 and its log near 26.7.
         * Only the constant matters, not its provenance: it shifts every English word equally
         * and so cannot reorder them, it only sets where they sit against Chinese and emoji.
         */
        private const val LOG_CORPUS_TOTAL = 26.67f

        /**
         * A glide needs two keys to be a glide at all. One-letter entries ("a", "I") can only
         * ever be typed by tapping, and having them here would let a sloppy tap that drifted a
         * key's width decode as a word.
         */
        private const val MIN_LETTERS = 2

        private fun key(first: Char, last: Char) = (first - 'a') * 26 + (last - 'a')

        fun load(input: InputStream): Lexicon {
            val words = ArrayList<String>(48_000)
            val letters = ArrayList<String>(48_000)
            val frequencies = ArrayList<Int>(48_000)
            val grouped = HashMap<Int, MutableList<Int>>()

            input.bufferedReader().useLines { lines -> lines.forEach { line -> read(line, words, letters, frequencies, grouped) } }

            return Lexicon(
                words = words,
                letters = letters,
                logFrequency = IntArray(frequencies.size) { frequencies[it] },
                buckets = grouped.mapValues { (_, list) -> IntArray(list.size) { list[it] } },
            )
        }

        private fun read(
            line: String,
            words: MutableList<String>,
            letters: MutableList<String>,
            frequencies: MutableList<Int>,
            grouped: MutableMap<Int, MutableList<Int>>,
        ) {
            if (line.isEmpty() || line[0] == '#') return
            val tab = line.indexOf('\t')
            if (tab <= 0) return
            val word = line.substring(0, tab)
            val frequency = line.substring(tab + 1).trim().toIntOrNull() ?: return
            val glided = word.lowercase().filter { it in 'a'..'z' }
            if (glided.length < MIN_LETTERS) return

            val index = words.size
            words += word
            letters += glided
            frequencies += frequency
            grouped.getOrPut(key(glided.first(), glided.last())) { ArrayList() } += index
        }

        /** For tests and for a build with no asset: a lexicon over a handful of words. */
        fun of(vararg entries: Pair<String, Int>): Lexicon =
            load(entries.joinToString("\n") { "${it.first}\t${it.second}" }.byteInputStream())
    }
}

/** The asset [Lexicon.load] reads, generated by `tools/build_lexicon.py`. */
const val LEXICON_ASSET = "lexicon_en.tsv"
