#!/usr/bin/env python3
"""
Generates the pinyin syllable table read by Syllables.kt.

The inventory is not a language fact to be looked up and typed in -- it is whatever the shipped
dictionary actually uses, including rime-ice's spelling conventions (`lve`/`nve` rather than
`lüe`/`nüe`, and `biang`). Writing it out by hand invites the one bug that is invisible in
review: a syllable in the asset that the segmenter refuses to split, so a word that is in the
dictionary can never be typed.

So it is read back out of the built asset and printed as Kotlin:

    tools/gen_syllable_table.py --dict app/src/main/assets/pinyin.bin \
        --out app/src/main/java/com/offlinekeyboard/ime/pinyin/SyllableTable.kt

Re-run it after tools/build_pinyin_dict.py whenever the upstream data changes. The unit tests
assert the two agree, so a stale table fails the build rather than the keyboard.
"""

from __future__ import annotations

import argparse
import struct

SEC_SYLLABLES = 1


def read_varint(data: bytes, pos: int) -> tuple[int, int]:
    result = 0
    shift = 0
    while True:
        byte = data[pos]
        pos += 1
        result |= (byte & 0x7F) << shift
        if not byte & 0x80:
            return result, pos
        shift += 7


def read_string(data: bytes, pos: int) -> tuple[str, int]:
    length, pos = read_varint(data, pos)
    return data[pos:pos + length].decode("utf-8"), pos + length


def syllables_of(path: str) -> list[str]:
    data = open(path, "rb").read()
    # Only the syllable section is read here, and its layout is the same in both formats.
    if data[:4] not in (b"PYD2", b"PYD3"):
        raise SystemExit(f"{path}: not a pinyin dictionary (bad magic {data[:4]!r})")
    _version, count = struct.unpack_from("<II", data, 4)
    pos = 12
    sections = {}
    for _ in range(count):
        sec_id, offset, length = struct.unpack_from("<III", data, pos)
        pos += 12
        sections[sec_id] = (offset, length)
    offset, _length = sections[SEC_SYLLABLES]
    total = struct.unpack_from("<I", data, offset)[0]
    pos = offset + 4
    out = []
    for _ in range(total):
        syllable, pos = read_string(data, pos)
        out.append(syllable)
    return out


HEADER = '''package com.offlinekeyboard.ime.pinyin

/**
 * Every pinyin syllable the shipped dictionary uses.
 *
 * GENERATED by tools/gen_syllable_table.py from app/src/main/assets/pinyin.bin -- do not edit.
 * Regenerate after rebuilding the dictionary; SyllablesTest asserts the two still agree, so a
 * stale table fails the build instead of quietly refusing to segment a word.
 *
 * These are the dictionary's spellings, not a textbook's: rime-ice writes `lve`/`nve` for
 * `lüe`/`nüe` because a phone keyboard has no `ü` key, and includes `biang`. A segmenter working
 * from a prettier list would reject input the dictionary can answer.
 */
internal object SyllableTable {
    /** Sorted, so it can be binary-searched and so the order is stable across regenerations. */
    val ALL: Array<String> = arrayOf(
'''

FOOTER = '''    )

    /** Longest syllable in [ALL], the most letters a single syllable can consume. */
    val MAX_LENGTH: Int = ALL.maxOf { it.length }
}
'''


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--dict", default="app/src/main/assets/pinyin.bin")
    ap.add_argument("--out",
                    default="app/src/main/java/com/offlinekeyboard/ime/pinyin/SyllableTable.kt")
    args = ap.parse_args()

    syllables = sorted(set(syllables_of(args.dict)))
    if not syllables:
        raise SystemExit("no syllables in dictionary")

    lines = []
    row: list[str] = []
    for syllable in syllables:
        row.append(f'"{syllable}"')
        if len(row) == 8:
            lines.append("        " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("        " + ", ".join(row) + ",")

    with open(args.out, "w", encoding="utf-8") as f:
        f.write(HEADER)
        f.write("\n".join(lines))
        f.write("\n")
        f.write(FOOTER)

    print(f"wrote {args.out}: {len(syllables)} syllables, "
          f"longest {max(len(s) for s in syllables)}")


if __name__ == "__main__":
    main()
